# Generated by Django 4.0.3 on 2022-04-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimereport', '0003_crimereport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='categories',
            field=models.CharField(choices=[('Anti-social behaviour', 'Anti-social behaviour'), ('Bicycle-theft', 'Bicycle-theft'), ('Burglary', 'Burglary'), ('Criminal damage and arson', 'Criminal damage and arson'), ('Drugs', 'Drugs'), ('Other theft', 'Other theft'), ('Possession of weapons', 'Possession of weapons'), ('Public order', 'Public order'), ('Robbery', 'Robbery'), ('Shoplifting', 'Shoplifting'), ('Theft from the person', 'Theft from the person'), ('Vehicle crime', 'Vehicle crime'), ('Violence and sexual offences', 'Violence and sexual offences'), ('Other crime', 'Other crime')], default='Picking option', max_length=100),
        ),
    ]
