# Generated by Django 4.0.4 on 2022-04-15 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crimereport', '0004_crimereport_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='crime_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='categories',
            field=models.CharField(choices=[('anti-social-behaviour', 'Anti-social behaviour'), ('bicycle-theft', 'Bicycle-theft'), ('burglary', 'Burglary'), ('criminal-damage-arson', 'Criminal damage and arson'), ('drugs', 'Drugs'), ('other-theft', 'Other theft'), ('possession-of-weapons', 'Possession of weapons'), ('public-order', 'Public order'), ('robbery', 'Robbery'), ('shoplifting', 'Shoplifting'), ('theft-from-the-person', 'Theft from the person'), ('vehicle-crime', 'Vehicle crime'), ('violent-crime', 'Violence and sexual offences'), ('other-crime', 'Other crime')], default='Picking option', max_length=100),
        ),
        migrations.AlterField(
            model_name='crimereport',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=120),
        ),
    ]
