# Generated by Django 4.0.4 on 2022-04-15 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crimereport', '0006_alter_crimereport_crime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='crime_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
