# Generated by Django 4.0.4 on 2022-04-29 11:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimereport', '0012_alter_crimereport_crime_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereport',
            name='crime_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2022, 4, 29))]),
        ),
    ]
